---
- name: Provision EC2 instances
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    key_name: "YOUR_KEY_PAIR_NAME"
    region: "YOUR_REGION"
    image: "ami-0c55b159cbfafe1f0"  # Amazon Linux 2 LTS
    instance_type: "t2.micro"
    security_group: "YOUR_SECURITY_GROUP_ID"
    subnet_id: "YOUR_SUBNET_ID"
    count: 2
  
  tasks:
    - name: Launch EC2 instances
      ec2:
        region: "{{ region }}"
        image: "{{ image }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        group_id: "{{ security_group }}"
        vpc_subnet_id: "{{ subnet_id }}"
        count: "{{ count }}"
        wait: true
      register: ec2_instances

    - name: Add new instances to host group
      add_host:
        name: "{{ item.public_ip }}"
        groups: ec2_instances
      with_items: "{{ ec2_instances.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        delay: 10
        timeout: 320
        state: started
      with_items: "{{ ec2_instances.instances }}"

- name: Configure EC2 instances
  hosts: ec2_instances
  become: true
  become_user: ec2-user
  gather_facts: True

  tasks:
    - name: Install necessary packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - git

    - name: Start httpd service
      service:
        name: httpd
        state: started
        enabled: true
