---
- name: install Apache and Upload to my servers
  hosts: all
  become: yes

  vars:
    - source_files: ./Mywebsite.html
    - dest_file: /var/www/html

  tasks:
    - name: Install Apache Web Server
      yum:
        name: httpd
        state: latest

    - name: Copy HTML file to server
      copy:
        src: "{{ source_files }}"
        dest: "{{ dest_file }}"
        mode: "0555"
      notify: Restart Apache

    - name: Start web servers and make enable onbooot
      service:
        name: httpd
        state: started
        enabled: yes

  handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted
