---
- name: loops
  hosts: Slave1
  become: yes

  tasks:
  - name: Hello
    debug: msg="Hello {{ item }}"
    loop:
      - "John"
      - "Adam"
      - "Sam"
      - "Olivia"

  - name: Loop Until example
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("ZZZZ") == false

  - name: Print Output final version
    debug:
      var: output.stdout
