---
# tasks file for deploy_apache
- name: Install Apache Web Server
  yum:
    name: httpd
    state: latest

- name: Generate index.html
  template:
    src: index.j2
    dest: "{{ dest_folder }}/index.html"
    mode: 0555
  notify: Restart Apache
